git add Sources/EXPECTED.md
git add "Sources/Fonctionnalit\303\251s A Tester.ods"
git add Sources/Plan_de_tests.odt
git add Sources/Principes.odt
git add Sources/README.md
git add Sources/SAW.odt
git add Sources/SBB_application-PoC.odt
git add Sources/SBB_pipelineCICD.odt
git add Sources/SBB_pipelineCICD.save.odt
git add Sources/diagrammes.odp
git add Sources/installation du pipeline.md
git add Sources/installation_du_pipeline.md
git add Sources/pipeline.jpg
git add Sources/pipeline.odg
git add Sources/tableauDeSourcing.ods
git add Sources/trace-log.md
git add exemples/DockerIntegration.old
git add exemples/Helloworld/src/main/java/com/openclassrooms/helloworld/model/HelloWorld.java
git add exemples/Helloworld/src/main/java/com/openclassrooms/helloworld/service/BusinessService.java
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/vcs.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/workspace.xml
git add exemples/emeregency-system/
git add exemples/helloworld/.gitignore
git add exemples/helloworld/.mvn/wrapper/maven-wrapper.jar
git add exemples/helloworld/.mvn/wrapper/maven-wrapper.properties
git add exemples/helloworld/mvnw
git add exemples/helloworld/mvnw.cmd
git add exemples/helloworld/pom.xml
git add exemples/helloworld/src/main/java/org/solarhis/helloworld/HelloworldApplication.java
git add exemples/helloworld/src/main/resources/application.properties
git add exemples/helloworld/src/test/java/org/solarhis/helloworld/HelloworldApplicationTests.java
git add Sources/dev/
git add Sources/doc/
git add exemples/Helloworld/.gitignore
git add exemples/Helloworld/.mvn/
git add exemples/Helloworld/bin/
git add exemples/Helloworld/mvnw
git add exemples/Helloworld/mvnw.cmd
git add exemples/Helloworld/pom.xml
git add exemples/Helloworld/src/main/java/com/openclassrooms/helloworld/HelloworldApplication.java
git add exemples/Helloworld/src/main/resources/
git add exemples/Helloworld/src/test/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/.gitignore
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/LOAD-BALANCER-WITH-API-GATEWAY.iml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/compiler.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/encodings.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/jarRepositories.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/libraries/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/misc.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/.idea/modules.xml
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/README.md
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/api-gateway/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/images/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/micro-service-client/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/micro-service-server/
git add exemples/LOAD-BALANCER-WITH-API-GATEWAY/netflix-eureka-naming-server/
git add exemples/emergency-system/
git add exemples/netflix-eureka-naming-server/

